### ISSUE TITLE
Problemas com palavras em comentários

### ISSUE THREAD

**Issue by mufernando** [lageIBUSP/notaR-legacy#22]
Em alguns exercícios é pedido para que não use a função nativa do R. Caso seja inserido um script com parte do nome da função dentro de um comentário, o notaR retorna um aviso de que não pode usar tal função.

Resumindo: ignorar a busca de palavras "proibidas" em comentários

**Comment by andrechalom** [comment]
O problema é que a busca de palavras proibidas é um feature de segurança que acabou sendo reutilizado para fins didáticos. E ele é feito pela camada PHP, para que isso nem chegue a ser processado pelo R. Sendo de segurança, qualquer processamento do texto para tentar melhorar a situação introduz risco: parar de procurar palavras proibidas depois de um # pode deixar alguém passar com uma chamada de system na mesma linha que tem "#", por exemplo - o que não é um comentário.

**Comment by andrechalom** [comment]
Uma alternativa possível se esse problema estiver causando muita confusão é simplesmente parar de usar a interface de palavras proibidas para efeito didático.

**Comment by piklprado** [comment]
O fim didático são exercícios que devem ser feitos sem algumas funções,
correto? Isso me parece importante de preservar, mesmo que o preço seja
impedir de usar o nome em comentários.  Isso pode ser contornado de várias
maneiras (mudando de alguma forma o nome da função no comentários, usando
maiúsculas p.ex).

Abrs

PI

Em 29 de março de 2016 12:44, Andre Chalom notifications@github.com
escreveu:

> Uma alternativa possível se esse problema estiver causando muita confusão
> é simplesmente parar de usar a interface de palavras proibidas para efeito
> didático.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/lageIBUSP/notaR/issues/22#issuecomment-202966981

## 

*Paulo Inácio de Knegt López de Prado
*Depto. de Ecologia - Instituto de Biociências -
USPhttp://ecologia.ib.usp.br/let http://ecologia.ib.usp.br/get
Rua do Matão, travessa 14, nº 321
Cid. Universitária, São Paulo - SP - Brasil
CEP 05508-900
+55-11-30910963 (sala)
+55-11-30917600 (Secretaria)

**Comment by andrechalom** [comment]
A princípio, eu concordo que é melhor manter o uso atual do que remove-lo
por medo de confusão.

Pensando bem, acho possível separar os dois casos no código, com o uso de
segurança permanecendo estrito e o uso "didático" permitindo algum tipo de
verificação (está em um #comentário? está "quoted"?). Se alguém quiser
alterar o código e submeter um pull request, ficarei grato.

2016-03-29 14:00 GMT-03:00 Paulo Inácio Prado notifications@github.com:
